version: '3.8'


networks:
    app-m-network:
      driver: bridge
services: 
    db:
        image: mysql:8.0.24
        networks:
            - app-m-network    
        environment: 
            - MYSQL_DATABASE=novedades
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_USER=testuser
            - MYSQL_TCP_PORT=3306
        ports: 
            - '3306:3306'
        expose: 
            - '3306'
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./server:/usr/src/server
        depends_on:
            - db
        networks:
            - app-m-network   
        environment: 
            - NODE_ENV=test
            - HOST=db